name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Dock
        run: 
          docker build -t miagegr2 .
          docker run -p 5000:8080 miagegr2
          curl --header "Content-Type: application/json" --request GET  http://localhost:5000/cars